title: Tactile theme
description: Tactile is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Roadbook Recorder]
description: [You may have heard of a roadbook being used by rally drivers in such events as the Dakar Rally.  Roadbooks are used in all rallies. A roadbook is arranged in the form of a table. Each line describes a significant point on the route, for example, a crossroads, a fork, a curiosity to see or a dangerous point. Instead of designing the roadbooks by hand, Roadbook Recorder offers an easy solution for automatic generation of these tables, making it convenient for rally organizers.]